name: Deploy Workflow

on:
  push:
    branches:
      - master  # when a push is executed in the master

jobs:
  deploy:
    runs-on: self-hosted  
    strategy:
      matrix:
        runner: ["isa","carlos","karen"]        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Deploy to EC2
        run: |
          pm2 reload DesingProject

