name: Deploy Workflow

on:
  push:
    branches:
      - main  # when a push is executed in the main branch

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Deploy to EC2
        run: |
          pm2 reload DesingProject

